### ISSUE TITLE
Migrate projects-cache property to configurable list instead of comma separated string

### ISSUE THREAD

**Issue by conorheffron** [conorheffron/ironoc#203]
Migrate `net.ironoc.portfolio.github.api.endpoint.projects-cache` property to configurable list instead of comma separated string. See example below of the current (AS-IS) state vs expected (TO-BE) format which is more readable and easier to manage. 

**as-is**
```
net:
  ironoc:
    portfolio:
      github:
        job-enable: true
        cron-job: "0 1 1 ? * *"
        timeout:
          connect: 100000
          read: 100000
        instance-follow-redirects: true
        follow-redirects: true
        api:
          endpoint:
            repos: https://api.github.com/users/{username}/repos?per_page={per_page}&page={page}
            user-ids-cache: conorheffron
            issues: https://api.github.com/repos/{username}/{repo}/issues?per_page={per_page}&page={page}
            projects-cache: "bio-cell-red-edge,booking-sys,cbio-skin-canc,fun-with-r,gene-expr"
```

**to-be**
```
net:
  ironoc:
    portfolio:
      github:
        job-enable: true
        cron-job: "0 1 1 ? * *"
        timeout:
          connect: 100000
          read: 100000
        instance-follow-redirects: true
        follow-redirects: true
        api:
          endpoint:
            repos: https://api.github.com/users/{username}/repos?per_page={per_page}&page={page}
            user-ids-cache: conorheffron
            issues: https://api.github.com/repos/{username}/{repo}/issues?per_page={per_page}&page={page}
            projects-cache:
             - bio-cell-red-edge
             - booking-sys
             - cbio-skin-canc
             - fun-with-r
             - gene-expr
```
